services:
  task0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task0
    ports:
      - "8000:8000"
    command: gunicorn hng12_task1.wsgi:application --bind 0.0.0.0:8000
